export const actionTypes = {
  GET_MOVIES:'GET_MOVIES',
  GET_SERIES:'GET_SERIES',
  GET_MOVIES_REQUEST: 'GET_MOVIES_REQUEST',
  GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
  GET_MOVIES_FAILURE: 'GET_MOVIES_FAILURE',
  GET_SERIES_REQUEST: 'GET_SERIES_REQUEST',
  GET_SERIES_SUCCESS: 'GET_SERIES_SUCCESS',
  GET_SERIES_FAILURE: 'GET_SERIES_FAILURE',
  CHANGE_HEADER_TITLE: 'CHANGE_HEADER_TITLE'
};
